import React, { useState } from 'react';
import confetti from 'canvas-confetti';
import sounds from '../audio/soundEffects';

export default function FinalScene({
  girlfriendName = 'Nonsense 🙃',
  specialDate = 'Happy Birthday Nonsense🙃',
  personalMessage = 'Bss aise hi saath rehna hmesha',
  onReplay,
}) {
  const [isLetterOpen, setIsLetterOpen] = useState(false);
  const [heartFloats, setHeartFloats] = useState([]);

  // Burst glowing floating hearts on user tap
  const handleTapForLove = (e) => {
    sounds.playTap();
    sounds.playSparkle();

    const rect = e.currentTarget.getBoundingClientRect();
    const originX = rect.left + rect.width / 2;
    const originY = rect.top;

    const newHearts = Array.from({ length: 6 }).map((_, i) => ({
      id: Date.now() + i,
      x: originX + (Math.random() - 0.5) * 60,
      y: originY,
      size: Math.random() * 16 + 22,
      emoji: ['❤️', '💖', '💕', '🥰', '✨'][Math.floor(Math.random() * 5)],
    }));

    setHeartFloats((prev) => [...prev, ...newHearts]);

    confetti({
      particleCount: 25,
      spread: 60,
      origin: { x: originX / window.innerWidth, y: originY / window.innerHeight },
      colors: ['#FF4B72', '#FFA6B8', '#FFE066'],
      ticks: 120,
      gravity: 0.4,
      scalar: 0.9,
    });

    setTimeout(() => {
      setHeartFloats((prev) => prev.filter((h) => !newHearts.includes(h)));
    }, 1800);
  };

  const handleOpenEnvelope = () => {
    sounds.playTap();
    sounds.playSparkle();
    sounds.playWhoosh();
    setIsLetterOpen(true);
  };

  return (
    <div className="relative w-full h-full min-h-screen flex flex-col items-center justify-center bg-gradient-to-b from-[#FFF5F7] via-[#FAF7F2] to-[#FFF0F3] px-4 py-8 select-none overflow-hidden">

      {/* Twilight romantic aura in background */}
      <div className="absolute w-[600px] h-[600px] bg-gradient-to-tr from-rose-200/35 via-pink-100/25 to-amber-100/20 rounded-full blur-3xl pointer-events-none animate-pulse-slow" />

      {/* Floating hearts generated by tap */}
      {heartFloats.map((h) => (
        <span
          key={h.id}
          className="fixed pointer-events-none z-50 animate-[floatUpFade_1.8s_ease-out_forwards]"
          style={{
            left: `${h.x}px`,
            top: `${h.y}px`,
            fontSize: `${h.size}px`,
            filter: 'drop-shadow(0 4px 10px rgba(255, 60, 100, 0.4))',
          }}
        >
          {h.emoji}
        </span>
      ))}

      {/* Main Content Card */}
      <div className="relative z-10 max-w-md w-full flex flex-col items-center text-center">

        {/* Soft floating glowing emblem */}
        <div className="relative mb-4">
          <div className="w-18 h-18 rounded-full bg-gradient-to-tr from-[#FF4B72] to-[#FF8FA3] flex items-center justify-center text-3xl shadow-xl shadow-rose-400/30 animate-romantic-float p-4">
            💖
          </div>
          <div className="absolute -top-1 -right-1 text-lg animate-spin text-amber-300">
            ✨
          </div>
        </div>

        {/* Angel's Name */}
        <div className="mb-3">
          <span className="text-xs uppercase tracking-[0.3em] text-[#B06D7D] font-semibold">
            To My Dearest
          </span>
          <h1 className="text-4xl md:text-5xl font-serif text-[#2B141C] mt-0.5 font-normal tracking-tight">
            {girlfriendName}
          </h1>
          <div className="w-16 h-[2px] bg-gradient-to-r from-transparent via-[#E62248] to-transparent mx-auto mt-2" />
        </div>

        {/* Romantic Core Message Card */}
        <div className="glass-card rounded-3xl p-6 md:p-8 my-3 shadow-xl border border-white/80 w-full">
          <p className="font-serif text-lg md:text-xl text-[#4A2D35] italic leading-relaxed">
            "{personalMessage}"
          </p>

          {specialDate && (
            <div className="mt-3 pt-3 border-t border-rose-100/80 flex items-center justify-center gap-2 text-xs font-sans text-[#A66877] uppercase tracking-wider">
              <span>Special Moment:</span>
              <span className="font-semibold text-[#E62248]">{specialDate}</span>
            </div>
          )}
        </div>

        {/* SLEEK, PROPERLY ALIGNED BUTTONS (Identical height, responsive, no awkward wrapping) */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 w-full mt-3">

          {/* Secret Love Letter Button */}
          <button
            onClick={handleOpenEnvelope}
            className="w-full h-12 px-5 rounded-full bg-white/95 border border-rose-300 text-[#C42E4B] font-semibold text-sm shadow-md hover:shadow-lg hover:bg-rose-50 hover:scale-105 active:scale-95 transition-all duration-200 cursor-pointer flex items-center justify-center gap-2 whitespace-nowrap"
          >
            <span className="text-base">💌</span>
            <span>Read Letter</span>
          </button>

          {/* Tap For Love Spawner */}
          <button
            onClick={handleTapForLove}
            className="w-full h-12 px-5 rounded-full bg-gradient-to-r from-[#FF4B72] to-[#E62248] text-white font-semibold text-sm shadow-md shadow-rose-500/25 hover:shadow-lg hover:shadow-rose-500/40 hover:scale-105 active:scale-95 transition-all duration-200 cursor-pointer flex items-center justify-center gap-2 whitespace-nowrap"
          >
            <span className="text-base">💖</span>
            <span>Tap for Love</span>
          </button>
        </div>

        {/* Clean Footer Note - NO Edit Details link */}
        <div className="mt-6 flex flex-col items-center gap-2">
          <p className="text-[11px] tracking-[0.25em] uppercase text-[#A66E7A] font-sans">
            Made with ❤️, just for you.
          </p>

          {/* Replay Surprise Button */}
          <button
            onClick={() => {
              sounds.playTap();
              sounds.playWhoosh();
              if (onReplay) onReplay();
            }}
            className="text-xs text-[#8A505E] hover:text-[#E62248] transition-colors flex items-center gap-1.5 cursor-pointer underline underline-offset-4 mt-1"
          >
            <span>↺</span>
            <span>Replay Surprise</span>
          </button>
        </div>

      </div>

      {/* SECRET LOVE LETTER MODAL WITH WAX SEAL */}
      {isLetterOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 backdrop-blur-sm p-4 animate-fade-in">
          <div className="relative max-w-lg w-full bg-[#FFFDF9] rounded-3xl p-6 md:p-10 shadow-2xl border border-rose-200 transform animate-[scaleUp_0.35s_ease-out]">

            {/* Close button */}
            <button
              onClick={() => {
                sounds.playTap();
                setIsLetterOpen(false);
              }}
              className="absolute top-4 right-4 w-8 h-8 rounded-full bg-rose-50 text-rose-400 hover:bg-rose-100 flex items-center justify-center text-sm cursor-pointer transition-colors"
            >
              ✕
            </button>

            {/* Wax Seal Header */}
            <div className="flex flex-col items-center mb-5">
              <div className="w-14 h-14 rounded-full bg-[#C41E3A] border-4 border-[#A3162D] text-white flex items-center justify-center text-xl shadow-lg shadow-rose-900/30">
                ♡
              </div>
              <span className="font-serif italic text-sm text-[#A66E7A] mt-2">
                Handwritten with endless adoration
              </span>
            </div>

            {/* Letter Body */}
            <div className="font-handwriting text-2xl md:text-3xl text-[#3D262C] leading-relaxed space-y-4 max-h-[60vh] overflow-y-auto pr-2">
              {<p>Abhi likha hai😅,</p>
/*
              <p>
                From the moment you walked into my life, everything became brighter, warmer, and so much softer.
              </p>

              <p>
                Thank you for being my safest home, my loudest laughter, and my gentlest peace. On your birthday and every single day that follows, {personalMessage}.
              </p>

              <p className="pt-2">
                Forever yours, <br />
                With all my heart ❤️
              </p> */}
            </div>

            {/* Bottom seal */}
            <div className="mt-5 pt-3 border-t border-rose-100 flex justify-between items-center text-xs font-sans text-rose-400">
              <span>{specialDate}</span>
              <span>Always &amp; Forever ✨</span>
            </div>
          </div>
        </div>
      )}

      <style>{`
        @keyframes floatUpFade {
          0% {
            opacity: 1;
            transform: translateY(0) scale(0.8) rotate(0deg);
          }
          100% {
            opacity: 0;
            transform: translateY(-160px) scale(1.3) rotate(20deg);
          }
        }
        @keyframes scaleUp {
          0% {
            opacity: 0;
            transform: scale(0.9) translateY(20px);
          }
          100% {
            opacity: 1;
            transform: scale(1) translateY(0);
          }
        }
      `}</style>
    </div>
  );
}
